src/SFA.DAS.Forecasting.Azure.Resources/Get-PfxPkcs12Base64String.ps1, src/SFA.DAS.Forecasting.Azure.Resources/SFA.DAS.Forecasting.Azure.Resources.deployproj, src/SFA.DAS.Forecasting.Azure.Resources/deployments/keyvault-resources.json, src/SFA.DAS.Forecasting.Azure.Resources/deployments/web-app-resources.json, src/SFA.DAS.Forecasting.Azure.Resources/parameters.json, src/SFA.DAS.Forecasting.Azure.Resources/template.json
Chaps - can you review please and let me merge. I think I've made the release definition changes but just need to hit save when I merge. Cheers
=> Additional KV App Settings and add cert from KV

src/SFA.DAS.Forecasting.Web/Attributes/AuthorizeForecastingAttribute.cs, src/SFA.DAS.Forecasting.Web/Controllers/ForecastingController.cs, src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj
=> Added attribute to allow loopback to access fcast

src/SFA.DAS.Forecasting.Application.UnitTests/Balance/BalanceHandlerTests.cs, src/SFA.DAS.Forecasting.Application.UnitTests/SFA.DAS.Forecasting.Application.UnitTests.csproj, src/SFA.DAS.Forecasting.Application.UnitTests/packages.config, src/SFA.DAS.Forecasting.Application/Balance/Services/AccountBalanceService.cs, src/SFA.DAS.Forecasting.Application/Balance/Services/DevAccountBalanceService.cs, src/SFA.DAS.Forecasting.Application/Balance/Services/IAccountBalanceService.cs, src/SFA.DAS.Forecasting.Application/Projections/Handlers/GetAccountBalanceHandler.cs, src/SFA.DAS.Forecasting.Application/SFA.DAS.Forecasting.Application.csproj, src/SFA.DAS.Forecasting.Application/packages.config, src/SFA.DAS.Forecasting.Database/Tables/Balance.sql, src/SFA.DAS.Forecasting.Domain.UnitTests/Balance/CurrentBalanceTests.cs, src/SFA.DAS.Forecasting.StubApi.Functions/SFA.DAS.Forecasting.StubApi.Functions.csproj, src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj, src/SFA.DAS.Forecasting.Web/Web.config, src/SFA.DAS.Forecasting.Web/packages.config
Added new columns to the Balance database to store the TransferBalance and allowance
Updated references to SFA.DAS.Accounts.Types nuget package
=> now records the transfer balance

src/SFA.DAS.Forecasting.Web/App_Start/RouteConfig.cs
=> CI-772 routing removed to address issue

README.md
=> Update README for initial development setup

src/SFA.DAS.Forecasting.AcceptanceTests/App.config, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Feature/Process Payment Event.feature, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Feature/Process Payment Event.feature.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Steps/ProcessPaymentEventSteps.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/TestPayment.cs, src/SFA.DAS.Forecasting.AcceptanceTests/StepsBase.cs, src/SFA.DAS.Forecasting.Application.UnitTests/Payments/PaymentEventSuperficialValidatorTests.cs, src/SFA.DAS.Forecasting.Application/Commitments/Handlers/StoreCommitmentHandler.cs, src/SFA.DAS.Forecasting.Application/Payments/Mapping/PaymentMapper.cs, src/SFA.DAS.Forecasting.Application/Payments/Messages/PaymentCreatedMessage.cs, src/SFA.DAS.Forecasting.Application/Payments/Validation/PaymentEventSuperficialValidator.cs, src/SFA.DAS.Forecasting.Database/PostDeployment/Script.PostDeployment1.sql, src/SFA.DAS.Forecasting.Database/Tables/Commitment.sql, src/SFA.DAS.Forecasting.Database/Tables/Payment.sql, src/SFA.DAS.Forecasting.Domain.UnitTests/Commitments/EmployerCommitmentTests.cs, src/SFA.DAS.Forecasting.Domain/Commitments/EmployerCommitment.cs, src/SFA.DAS.Forecasting.Domain/Payments/EmployerPayment.cs, src/SFA.DAS.Forecasting.Models/Commitments/CommitmentModel.cs, src/SFA.DAS.Forecasting.Models/Payments/PaymentModel.cs, src/SFA.DAS.Forecasting.Payments.Functions/PaymentEventHttpFunction.cs
=> CI-621 -> Saving sending employer

src/SFA.DAS.Forecasting.Web/Views/Shared/_Layout.cshtml
Created on behalf of @abroodie
=> Added new GA tags

src/SFA.DAS.Forecasting.Web.UnitTests/OrchestratorTests/EstimationOrchestratorTests.cs, src/SFA.DAS.Forecasting.Web/ViewModels/EstimationTransferAllowanceVewModel.cs
Changed logic so that now the IsLessThanCost will show only if the
Remaining Allowance is less than 0
=> CI-866 - Change logic on IsLessThanCost property

src/SFA.DAS.Forecasting.Web/Extensions/DecimalExtensions.cs
Change so minus sign appears before pound symbol
=> CI-863 - Change to negative currency format

README.md, src/SFA.DAS.Forecasting.AcceptanceTests/App.config, src/SFA.DAS.Forecasting.AcceptanceTests/Infrastructure/Config.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Levy/Feature/PreLoadLevyEvents.feature, src/SFA.DAS.Forecasting.AcceptanceTests/Levy/Feature/PreLoadLevyEvents.feature.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Levy/Steps/PreLoadLevyEventsSteps.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Steps/Pre_LoadPaymentsSteps.cs, src/SFA.DAS.Forecasting.Application/Infrastructure/Registries/DefaultRegistry.cs, src/SFA.DAS.Forecasting.Application/Shared/Services/EmployerDataService.cs, src/SFA.DAS.Forecasting.Application/Shared/Services/EmployerDatabaseService.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/AllLevyDeclarationsPreLoadHttpFunction.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/LevyDeclarationPreLoadFunction.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/LevyDeclarationPreLoadHttpFunction.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/Models/PreLoadAllEmployersRequest.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/Models/PreLoadRequest.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/QueueNames.cs
* Reading from employer DB to get all employer ids for a period
* PreLoad tests now reading from EmployerDB (and loading test data)
=> CI-765 -> PreLoad Levy for all employers

src/SFA.DAS.Forecasting.AcceptanceTests/App.config, src/SFA.DAS.Forecasting.AcceptanceTests/Infrastructure/Config.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Feature/PreLoadPayments.feature, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Feature/PreLoadPayments.feature.cs, src/SFA.DAS.Forecasting.AcceptanceTests/Payments/Steps/Pre_LoadPaymentsSteps.cs, src/SFA.DAS.Forecasting.AcceptanceTests/SFA.DAS.Forecasting.AcceptanceTests.csproj, src/SFA.DAS.Forecasting.Application/Infrastructure/Registries/ConfigurationHelper.cs, src/SFA.DAS.Forecasting.Application/Infrastructure/Registries/DefaultRegistry.cs, src/SFA.DAS.Forecasting.Application/Payments/Messages/PreLoad/AllEmployersPreLoadPaymentRequest.cs, src/SFA.DAS.Forecasting.Application/Payments/Services/DevPaymentsEventsApiClient.cs, src/SFA.DAS.Forecasting.Application/SFA.DAS.Forecasting.Application.csproj, src/SFA.DAS.Forecasting.Application/Shared/Services/EmployerDatabaseService.cs, src/SFA.DAS.Forecasting.Functions.Framework/Logging/LoggerSetup.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/AllEmployersPaymentPreLoadHttpFunction.cs, src/SFA.DAS.Forecasting.PreLoad.Functions/GetEarningDetailsFunction.cs
* a period of year and month
* creating a msg for each employer and sending it to PreLoadPayment
=> CI-875 -> PreLoad all employers

src/SFA.DAS.Forecasting.AcceptanceTests/Levy/Feature/PreLoadLevyEvents.feature.cs, src/SFA.DAS.Forecasting.Web.UnitTests/SFA.DAS.Forecasting.Web.UnitTests.csproj, src/SFA.DAS.Forecasting.Web.UnitTests/ViewModels/FinancialYearTests.cs, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css, src/SFA.DAS.Forecasting.Web/Content/src/sass/_custom.scss, src/SFA.DAS.Forecasting.Web/Orchestrators/ForcastingOrchestrator.cs, src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj, src/SFA.DAS.Forecasting.Web/ViewModels/BalanceViewModel.cs, src/SFA.DAS.Forecasting.Web/ViewModels/EqualityComparer/FinancialYearIEqualityComparer.cs, src/SFA.DAS.Forecasting.Web/ViewModels/FinancialYear.cs, src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
=> CI-855  projection financial year

src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
https://skillsfundingagency.atlassian.net/browse/CI-891
=> CI-891 -> Updated text

src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css, src/SFA.DAS.Forecasting.Web/Content/src/sass/_custom.scss, src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
=> CI-890 -> Add survey to projection

src/SFA.DAS.Forecasting.Web/Content/dist/js/add-apprenticeship-custom.js, src/SFA.DAS.Forecasting.Web/Content/dist/js/apprenticeships.js, src/SFA.DAS.Forecasting.Web/Controllers/EstimationController.cs, src/SFA.DAS.Forecasting.Web/Extensions/StringExtension.cs, src/SFA.DAS.Forecasting.Web/Orchestrators/Estimations/EstimationOrchestrator.cs, src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj, src/SFA.DAS.Forecasting.Web/ViewModels/EditApprenticeshipsViewModel.cs, src/SFA.DAS.Forecasting.Web/ViewModels/Validation/EditApprenticeshipsViewModelValidator.cs, src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/EditApprenticeships.cshtml
* Edit page total funding can't go over total funding cap fix
* Edit page total funding correct value when loading page fix
--------------
JS add and edit will change a lot with Funding Band stories. 🐤 
/c
=> CI-911, CI-910

src/SFA.DAS.Forecasting.Application/Levy/Handlers/AllowAccountProjectionsHandler.cs, src/SFA.DAS.Forecasting.Application/Payments/Handlers/AllowAccountProjectionsHandler.cs, src/SFA.DAS.Forecasting.Domain/Projections/AccountProjection.cs
Only add the audit event if we are allowed to generate the projection
from waiting for the correct period
=> CI-920Add audit event after successful projection

src/SFA.DAS.Forecasting.Application/Projections/Services/AccountProjectionDataSession.cs, src/SFA.DAS.Forecasting.Database/Tables/AccountProjection.sql
Try and help with idempotencey of AccountProjection records. Using
merge statement to match on accountid, month and year.
=> CI-920 - Change insert statement to be merge

src/SFA.DAS.Forecasting.Application.UnitTests/Commitments/StoreCommitmentHandler/WhenIStoreCommitments.cs, src/SFA.DAS.Forecasting.Application/Commitments/Handlers/StoreCommitmentHandler.cs
Remove completion amount check from the handler as it is already done
in the payment superficial validator
=> CI-920 Remove completion amount check

src/SFA.DAS.Forecasting.Domain.UnitTests/Estimations/AccountEstimationTests.cs, src/SFA.DAS.Forecasting.Domain/Estimations/AccountEstimation.cs, src/SFA.DAS.Forecasting.Domain/Estimations/AccountEstimationProjectionRepository.cs, src/SFA.DAS.Forecasting.Web.AcceptanceTests/Infrastructure/ApprenticeshipDataService.cs, src/SFA.DAS.Forecasting.Web.AcceptanceTests/Infrastructure/DocumentSessionConnectionString.cs, src/SFA.DAS.Forecasting.Web.UnitTests/SFA.DAS.Forecasting.Web.UnitTests.csproj, src/SFA.DAS.Forecasting.Web.UnitTests/ViewModels/EstimationPageViewModelTests.cs, src/SFA.DAS.Forecasting.Web/Orchestrators/Estimations/EstimationOrchestrator.cs, src/SFA.DAS.Forecasting.Web/ViewModels/EstimationApprenticeshipViewModel.cs, src/SFA.DAS.Forecasting.Web/ViewModels/EstimationPageViewModel.cs, src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/CostEstimation.cshtml
Table under apprenticeships on estimated cost page is too wide. 
Waiting for Rajesh to make a decision on what to do.
/c
--
Suggested solution will not work
Unfortunately we cannot any Jas solutions on our applications due to accessibility’s standards. (Rajesh)
/c
=> CI-905 indicate apprenticeship type

src/SFA.DAS.Forecasting.Domain/Estimations/AccountEstimationProjection.cs, src/SFA.DAS.Forecasting.Models/Estimation/ApprenticeshipToAdd.cs, src/SFA.DAS.Forecasting.Web/Controllers/EstimationController.cs, src/SFA.DAS.Forecasting.Web/Orchestrators/Estimations/AddApprenticeshipOrchestrator.cs, src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj, src/SFA.DAS.Forecasting.Web/ViewModels/StartViweModel.cs, src/SFA.DAS.Forecasting.Web/ViewModels/TypeOfApprenticeshipViewModel.cs, src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/StartEstimation.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/TypeOfApprenticeships.cshtml
* Need new start page for transfers only
* Need to add link on 'tell us' page
=> CI-904 tell app type page

src/SFA.DAS.Forecasting.AcceptanceTests/Projections/Feature/Calculate co-investment amounts.feature, src/SFA.DAS.Forecasting.AcceptanceTests/Projections/Feature/Calculate co-investment amounts.feature.cs, src/SFA.DAS.Forecasting.Domain.UnitTests/Projection/AccountProjectionTests.cs, src/SFA.DAS.Forecasting.Domain/Projections/AccountProjection.cs
incorrect opening balance for levy run
=> CI-951 incorrect opening balance

src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css, src/SFA.DAS.Forecasting.Web/Content/src/sass/_custom.scss, src/SFA.DAS.Forecasting.Web/Content/src/sass/forms/_form-validation.scss, src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/CostEstimation.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/EditApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/StartEstimation.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/TypeOfApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Shared/_validationErrors.cshtml
- Typo fix for CI-993
- CSS fix for employer header
- Removed various duplicated MAIN tags
- Ensured all fields linked from error summaries can be seen
=> Ci 968 error summary

src/SFA.DAS.Forecasting.Web/SFA.DAS.Forecasting.Web.csproj, src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml
=> Fixed typo on Balance view 

src/SFA.DAS.Forecasting.Web/Content/dist/js/add-edit-functions.js
Change find on array to use a search instead to work in IE
=> CI-1020 Change find on array

src/SFA.DAS.Forecasting.Web/Content/dist/js/add-apprenticeship.js
- Calculate cost triggered as user types start year
- Remove ES6 arrow functions so works in IE11
=> Ci 1025 add app total cost

src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie6.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie7.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen-ie8.css, src/SFA.DAS.Forecasting.Web/Content/dist/css/screen.css, src/SFA.DAS.Forecasting.Web/Content/dist/js/add-apprenticeship.js, src/SFA.DAS.Forecasting.Web/Content/dist/js/screen.js, src/SFA.DAS.Forecasting.Web/Content/src/sass/_tables.scss, src/SFA.DAS.Forecasting.Web/Views/Estimation/AddApprenticeships.cshtml, src/SFA.DAS.Forecasting.Web/Views/Estimation/CostEstimation.cshtml
- Back links
- Tables column widths
=> CI-1025, CI-1016, CI-1035, CI-1036 Front end tickets

src/SFA.DAS.Forecasting.Application.UnitTests/Shared/PayrollDateServiceTests.cs, src/SFA.DAS.Forecasting.Application/Shared/Services/PayrollDateService.cs
Changed payroll date service to calculate the year part correctly
inline with the payroll month.
(cherry picked from commit 196893c1eaaf84b16c2f17dd10c43e333adfeb19)
=> CI-1088 - Change to PayrollDateService

src/SFA.DAS.Forecasting.Application/Shared/Services/DevHashingService.cs, src/SFA.DAS.Forecasting.Database/Tables/Payment.sql, src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml, src/SFA.DAS.Forecasting.Web/Web.config
This also enables expired funds
=> CI-1091 guidance message

src/SFA.DAS.Forecasting.Application.UnitTests/ExpiredFunds/ExpiredFundsServiceTests.cs, src/SFA.DAS.Forecasting.Application/ExpiredFunds/Service/ExpiredFundsService.cs, src/SFA.DAS.Forecasting.Application/Projections/Handlers/BuildAccountProjectionHandler.cs, src/SFA.DAS.Forecasting.Database/Tables/Payment.sql, src/SFA.DAS.Forecasting.Domain/Projections/AccountProjectionRepository.cs, src/SFA.DAS.Forecasting.Web/Views/Forecasting/Balance.cshtml, src/SFA.DAS.Forecasting.Web/Web.config
correct first month payment value used for expired funds
=> CI-898 correct first month payment value

src/SFA.DAS.Forecasting.Domain.UnitTests/Estimations/AccountEstimationProjectionTests.cs, src/SFA.DAS.Forecasting.Domain.UnitTests/Projection/AccountProjectionTests.cs, src/SFA.DAS.Forecasting.Web/Views/Shared/_Layout.cshtml
The build is failing because of a failing test which has been fixed in the branch - "CON-1025-upgrade-commitments_client-to-use-azure-ad". Once these changes are merged to master we need to rebase this branch with master for a successful build.
=> CON-1110-remove banner

azure/template.json
=> Making alerts deployment name shorter to faciliate deployment name char limit
